packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - electron
  - esbuild
  - unrs-resolver
allowBuilds:
  electron: true
  esbuild: true
  sqlite3: set this to true or false
  unrs-resolver: true
