import { useState } from 'react'
import { ChevronRight } from 'lucide-react'
import { Message, MessageContent } from '@/components/ui/message'
import { cn } from '@/lib/utils'
import type { ConversationMessage } from './chat-conversation-types'
import { MessageMeta, MessageStatusActions } from './chat-message-actions'
import { MessageBlockFrame, getInsetOverlayClass } from './chat-message-frame'
import { getMetadataAccessory } from './chat-message-metadata'

export const UserMessageBubble = ({
  message,
  onRewind,
  rewindDisabled,
  showMeta,
  wide,
}: {
  message: ConversationMessage
  onRewind?: (message: ConversationMessage) => void
  rewindDisabled?: boolean
  showMeta: boolean
  wide: boolean
}) => {
  const content = message.content
  const metadataAccessory = getMetadataAccessory(message.metadata)
  const runPrompt = content ? parseRunPromptContent(content) : null

  return (
    <Message className="group w-full min-w-0 justify-end">
      <div
        className={cn(
          'group/message flex w-full min-w-0 flex-col space-y-1 mb-2',
          wide ? 'items-stretch' : 'items-end',
          !wide && 'max-w-[920px]',
        )}
      >
        {showMeta ? <MessageMeta message={message} /> : null}
        {content ? (
          <MessageBlockFrame
            accessory={metadataAccessory}
            className={
              wide ? 'w-full max-w-full' : 'w-fit max-w-[calc(100%_-_10rem)]'
            }
            overlayClassName={wide ? getInsetOverlayClass('right') : undefined}
            overlay={
              <MessageStatusActions
                message={message}
                onRewind={onRewind}
                rewindDisabled={rewindDisabled}
              />
            }
            overlaySide={wide ? 'right' : 'left'}
          >
            {runPrompt ? (
              <RunPromptContent
                fullContent={content}
                messageId={message.id}
                prompt={runPrompt}
              />
            ) : (
              <MessageContent
                className={userMessageContentClass}
                id={message.id}
                markdown
              >
                {content}
              </MessageContent>
            )}
          </MessageBlockFrame>
        ) : null}
      </div>
    </Message>
  )
}

const userMessageContentClass =
  'max-w-full overflow-hidden rounded-lg bg-chat-user px-2.5 py-1.5 text-sm leading-5 text-chat-user-foreground prose-p:my-0 prose-pre:my-1.5 prose-ol:my-1 prose-ul:my-1 prose-li:my-0 prose-blockquote:my-1.5 prose-table:my-1.5 [&_*]:max-w-full [&_pre]:overflow-x-auto'

const RunPromptContent = ({
  fullContent,
  messageId,
  prompt,
}: {
  fullContent: string
  messageId: string
  prompt: ParsedRunPrompt
}) => {
  const [contextOpen, setContextOpen] = useState(false)

  return (
    <div className="min-w-0 max-w-full overflow-hidden rounded-lg bg-chat-user text-chat-user-foreground">
      <MessageContent
        className="max-w-full bg-transparent px-2.5 py-1.5 text-sm leading-5 prose-p:my-0 prose-pre:my-1.5 prose-ol:my-1 prose-ul:my-1 prose-li:my-0 [&_*]:max-w-full [&_pre]:overflow-x-auto"
        id={messageId}
        markdown
      >
        {prompt.visibleContent}
      </MessageContent>

      <button
        aria-expanded={contextOpen}
        className="flex w-full items-center gap-1 border-t border-border/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground transition-colors hover:text-foreground"
        onClick={() => setContextOpen((current) => !current)}
        type="button"
      >
        <ChevronRight
          className={cn(
            'h-3 w-3 transition-transform',
            contextOpen && 'rotate-90',
          )}
        />
        Run context
        <span className="font-normal">
          · metadata, workflow rules, full prompt
        </span>
      </button>

      {contextOpen ? (
        <MessageContent
          className="max-w-full border-t border-border/60 bg-transparent px-2.5 py-1.5 text-xs leading-5 text-muted-foreground prose-p:my-0 prose-pre:my-1.5 prose-ol:my-1 prose-ul:my-1 prose-li:my-0 [&_*]:max-w-full [&_pre]:overflow-x-auto"
          id={`${messageId}-run-context`}
          markdown
        >
          {fullContent}
        </MessageContent>
      ) : null}
    </div>
  )
}

type ParsedRunPrompt = {
  taskTitle: string | null
  visibleContent: string
}

const RUN_PROMPT_SECTION_HEADERS = [
  'Issue description:',
  'Task completion target:',
  'Prior issue context:',
  'Previous completed tasks:',
  'Agent-driven workflow:',
  'Task execution rules:',
]

/**
 * Detects agent run prompts generated by the API (issueTaskPrompts.ts) so the
 * scaffolding can be collapsed behind a "Run context" disclosure while the
 * human-authored parts (issue description / task target) stay visible.
 */
const parseRunPromptContent = (content: string): ParsedRunPrompt | null => {
  if (!content.startsWith('Issue: ')) {
    return null
  }

  const hasScaffold =
    content.includes('\nTask execution rules:') ||
    content.includes('\nAgent-driven workflow:')

  if (!hasScaffold) {
    return null
  }

  const description = extractRunPromptSection(content, 'Issue description:')

  if (!description) {
    return null
  }

  const target = extractRunPromptSection(content, 'Task completion target:')
  const taskTitle = extractRunPromptLine(content, 'Current task: ')

  const visibleContent = [
    taskTitle ? `**${taskTitle}**` : null,
    // Task runs lead with their completion target; issue runs lead with the
    // issue description. The full prompt stays available in the disclosure.
    target ?? description,
  ]
    .filter(Boolean)
    .join('\n\n')

  return { taskTitle, visibleContent }
}

const extractRunPromptSection = (content: string, header: string) => {
  const marker = `\n${header}\n`
  const markerIndex = content.indexOf(marker)

  if (markerIndex === -1) {
    return null
  }

  const start = markerIndex + marker.length
  let end = content.length

  for (const candidate of RUN_PROMPT_SECTION_HEADERS) {
    if (candidate === header) {
      continue
    }

    const candidateIndex = content.indexOf(`\n${candidate}`, start)

    if (candidateIndex !== -1 && candidateIndex < end) {
      end = candidateIndex
    }
  }

  return content.slice(start, end).trim() || null
}

const extractRunPromptLine = (content: string, prefix: string) => {
  const line = content
    .split('\n')
    .find((candidate) => candidate.startsWith(prefix))

  return line ? line.slice(prefix.length).trim() || null : null
}
